name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      
      - name: Build
        run: cargo build --bin qemu-uefi

      - name: Unit tests (lib)
        run: cargo ktest --lib

  integration-tests:
    needs: build-and-unit-test
    name: Integration Test — ${{ matrix.test }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test:
          - test-boot
          - test-should-panic
          - test-stack-overflow
          - test-virtual-address-panic
          - test-should-page-fault
          - test-divide-by-zero-error

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run ${{ matrix.test }}
        run: cargo ktest --test ${{ matrix.test }}
